apiVersion: v2
version: 0.1.0
appVersion: v0.1.0
name: stucoin
description: A Helm chart for Kubernetes
home: https://github.com/cpprian/stucoin-backend
type: application
dependencies:
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.x
  - name: tasks
    version: 0.x.x
  - name: rewards
    version: 0.x.x
  - name: micro-competencies
    version: 0.x.x
  - name: bff
    version: 0.x.x
sources:
  - https://github.com/cpprian/stucoin-backend