mongodb:
  enabled: true

  image:
    repository: mongo
    tag: 4.2.23

  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

  persistence:
    mountPath: /data/db

users:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"
  
rewards:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"