mongodb:
  enabled: true

  image: 
    repository: mongo
    tag: 4.2.23
    
  auth:
    enabled: false
  
  readinessProbe:
    enabled: false
  
  livenessProbe:
    enabled: false

  persistence:
    mountPath: /data/db

tasks:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

bff:
  args:
    - "-tasksAPI"
    - "http://stucoin-tasks/tasks"
    - "-rewardsAPI"
    - "http://stucoin-rewards/rewards"
    - "-microCompetenciesAPI"
    - "http://stucoin-micro-competencies/micro-competencies"

rewards:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

micro-competencies:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"
    