mongodb:
  enabled: true

  image:
    repository: mongo
    tag: 4.2.23

  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

  persistence:
    mountPath: /data/db

tasks:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"
  
rewards:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

micro-competencies:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

bff:
  args:
    - "-tasksURI"
    - "http://stucoin-tasks/tasks"
    - "-rewardsURI"
    - "http://stucoin-rewards/rewards"
    - "-microCompetenciesURI"
    - "http://stucoin-micro-competencies/micro-competencies"