mongodb:
  enabled: true

  image: 
    repository: mongo
    tag: 4.2.23
    
  auth:
    enabled: false
  
  readinessProbe:
    enabled: false
  
  livenessProbe:
    enabled: false

  persistence:
    mountPath: /data/db

# Blogposts users values
users:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

# Blogposts website values
website:
  args:
    - "-tasksAPI"
    - "http://stucoin-users/tasks"
    - "-rewardsAPI"
    - "http://stucoin-posts/rewards"
    - "-microCompetenciesAPI"
    - "http://stucoin-comments/micro-competencies"

# Blogposts posts values
posts:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"

# Blogposts comments values
comments:
  args:
    - "-mongoURI"
    - "mongodb://stucoin-mongodb:27017/"
    