name: release

on: push

env: 
    REGISTRY: ghcr.io
    TASKS_IMAGE_NAME: "stucoin-tasks"
    REWARDS_IMAGE_NAME: "stucoin-rewards"
    MICRO_COMPETENCIES_IMAGE_NAME: "stucoin-micro-competencies"

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push the tasks image
              uses: docker/build-push-action@v3
              with:
                  context: ./tasks/
                  file: ./tasks/Dockerfile
                  push: true
                  tags: |
                      cpprian/${{ env.TASKS_IMAGE_NAME }}
                      ghcr.io/cpprian/${{ env.TASKS_IMAGE_NAME }}

            - name: Build and push the rewards image
              uses: docker/build-push-action@v3
              with:
                  context: ./rewards/
                  file: ./rewards/Dockerfile
                  push: true
                  tags: |
                      cpprian/${{ env.REWARDS_IMAGE_NAME }}
                      ghcr.io/cpprian/${{ env.REWARDS_IMAGE_NAME }}
        
            - name: Build and push the micro-competencies image
              uses: docker/build-push-action@v3
              with:
                  context: ./micro-competencies/
                  file: ./micro-competencies/Dockerfile
                  push: true
                  tags: |
                      cpprian/${{ env.MICRO_COMPETENCIES_IMAGE_NAME }}
                      ghcr.io/cpprian/${{ env.MICRO_COMPETENCIES_IMAGE_NAME }}